# -*- coding: utf-8 -*-
# Conteúdo da Trilha KitPC: do zero ao primeiro boot.
# Cada lição é um dicionário com: slug (usado na URL), bloco (1, 2 ou 3),
# bloco_nome (título do bloco), numero (ordem de exibição), titulo, resumo
# (aparece na listagem), paragrafos (corpo da lição, um item por parágrafo)
# e video_url (opcional — se você tiver um vídeo do YouTube que explica bem
# aquele passo, cole o link de EMBED aqui, ex: "https://www.youtube.com/embed/XXXXXXXXXXX".
# Deixe como None se não tiver vídeo pra essa lição — o site funciona normal sem ele).

LICOES = [
    {
        "slug": "pc-arriscado",
        "bloco": 1,
        "bloco_nome": "Começar do Zero (Perder o Medo)",
        "numero": 1,
        "titulo": "Montar um PC é arriscado?",
        "resumo": "Quebrando o medo de perder dinheiro e queimar peças.",
        "video_url": None,
        "paragrafos": [
            "Resposta curta: não, muito menos do que parece. Todas as peças de um computador são feitas com encaixes que só entram de um jeito. Se uma peça não está entrando fácil, isso é o próprio computador te avisando 'não é aqui' — nunca force.",
            "Guarde essa frase pro resto da trilha, ela vale pra tudo: <strong>se precisar fazer força, pare e olhe de novo antes de continuar.</strong> Encaixe certo entra suave, só empurrando levemente com a mão.",
            "O único risco real (e é fácil de evitar) é a eletricidade estática do seu próprio corpo — aquele choquinho que às vezes você leva ao tocar em uma maçaneta. Isso pode, em teoria, danificar uma peça eletrônica sensível. A solução é simples e vamos explicar em detalhes na lição 11: antes de tocar em qualquer peça, você encosta a mão em algo de metal pra 'descarregar' essa estática do seu corpo. Leva 2 segundos e resolve o problema inteiro.",
            "Fora isso, não existe outro jeito de 'quebrar' um PC sem querer. Você não vai apertar o parafuso errado e explodir nada, não vai ligar o cabo invertido e pegar fogo. As peças são feitas pensando em gente que nunca montou um PC antes — inclusive você.",
            "Milhares de pessoas sem nenhuma experiência técnica montam o primeiro PC sozinhas, seguindo um passo a passo como esse. Vá com calma, sem pressa, e você vai conseguir.",
        ],
    },
    {
        "slug": "pronto-ou-montar",
        "bloco": 1,
        "bloco_nome": "Começar do Zero (Perder o Medo)",
        "numero": 2,
        "titulo": "PC pronto ou montar peça por peça?",
        "resumo": "Vantagens, desvantagens e custo-benefício.",
        "video_url": None,
        "paragrafos": [
            "<strong>PC pronto</strong> é aquele que já vem montado de fábrica ou de loja — você compra, liga na tomada e já está usando no mesmo dia. A vantagem é a praticidade total. A desvantagem é que você geralmente paga um pouco mais caro pelo serviço de montagem, e às vezes as peças usadas dentro dele são versões mais simples do que parece pelo preço anunciado.",
            "<strong>Montar peça por peça</strong> significa que você mesmo escolhe e compra cada componente (processador, placa-mãe, memória, etc.) separadamente, e depois encaixa tudo. Dá um pouco mais de trabalho no início — mas é exatamente esse trabalho que essa trilha vai te ensinar a fazer, passo a passo.",
            "A vantagem de montar você mesmo é o controle: você decide gastar mais numa peça que importa pra você (por exemplo, a placa de vídeo, se você joga) e economizar em outra que importa menos (por exemplo, o gabinete, se a estética não é prioridade). Isso normalmente entrega mais desempenho pelo mesmo dinheiro do que um PC pronto equivalente.",
            "Não existe resposta 'certa' pra todo mundo. Se você quer resolver rápido e o preço não é o maior problema, PC pronto funciona bem. Se você tem um pouco de tempo, quer aprender e quer aproveitar melhor cada real gasto, montar você mesmo vale a pena — e é pra isso que essa trilha e o Montador de PC do KitPC existem.",
        ],
    },
    {
        "slug": "ferramentas-necessarias",
        "bloco": 1,
        "bloco_nome": "Começar do Zero (Perder o Medo)",
        "numero": 3,
        "titulo": "Ferramentas que você realmente precisa",
        "resumo": "O que separar antes de começar (e o que você não precisa comprar).",
        "video_url": None,
        "paragrafos": [
            "Notícia boa: você não precisa de uma caixa de ferramentas cheia. Na prática, 90% de uma montagem inteira é feita com <strong>uma única chave de fenda tipo Phillips</strong> (aquela com a pontinha em formato de cruz, tipo um sinal de mais), de tamanho médio — geralmente vendida como '#2'. Se você tem uma chave de fenda em casa com a ponta em cruz, ela provavelmente já serve.",
            "Separe também: uma mesa ou superfície firme e livre pra trabalhar (evite cama, tapete ou carpete — explicamos o porquê na lição 11), uma boa lâmpada ou luz ambiente, e um potinho pequeno ou pratinho só pra guardar os parafusos que forem sobrando — eles somem fácil se ficarem soltos na mesa.",
            "Sobre a tal 'pulseira antiestática': ela ajuda, mas não é obrigatória. Existe um truque de graça que resolve o mesmo problema: antes de tocar em qualquer peça, encoste a mão em alguma parte de metal sem pintura — pode ser a estrutura do próprio gabinete, ou a carcaça de uma geladeira/fogão (desligado no botão, mas ligado na tomada). Isso 'descarrega' a eletricidade estática do seu corpo antes que ela chegue nas peças.",
            "O que você <strong>não precisa</strong> comprar: kits de chave de precisão pra celular/eletrônica, pasta térmica extra (o cooler já vem com uma camada aplicada de fábrica, pronta pra usar), nem nenhuma ferramenta 'especial' de informática. Se sobrar um dinheirinho, é sempre melhor investir numa peça melhor do que numa ferramenta que você só vai usar uma vez na vida.",
        ],
    },
    {
        "slug": "glossario-basico",
        "bloco": 1,
        "bloco_nome": "Começar do Zero (Perder o Medo)",
        "numero": 4,
        "titulo": "Glossário rápido: os termos que todo iniciante ouve",
        "resumo": "CPU, GPU, RAM, SSD, fonte, placa-mãe — o que cada peça faz, em português simples.",
        "video_url": None,
        "paragrafos": [
            "Antes de seguir em frente, vale a pena fixar sete palavras. Elas vão aparecer o tempo todo no resto da trilha, e uma vez que você entende o que cada uma faz, o resto fica muito mais fácil de acompanhar.",
            "<strong>Processador (também chamado de CPU):</strong> é o 'cérebro' do computador. É a peça que faz os cálculos e comandos que fazem tudo acontecer, de abrir um aplicativo a rodar um jogo.",
            "<strong>Placa-mãe:</strong> é a peça grande e retangular onde todas as outras peças se encaixam, tipo uma base. É ela que decide quais processadores e memórias combinam com o seu PC — por isso a lição 7 é tão importante.",
            "<strong>Memória RAM:</strong> pense nela como a 'mesa de trabalho' do computador — é onde ficam guardadas, temporariamente, as informações dos programas que estão abertos naquele momento. Quanto mais RAM, mais coisa você consegue ter aberta ao mesmo tempo sem o PC travar ou ficar lento.",
            "<strong>Placa de vídeo (também chamada de GPU):</strong> é a peça responsável por processar imagens e gráficos. É essencial pra jogos e edição de vídeo/foto pesada. Pra uso básico (navegar na internet, estudar, trabalhar com texto), muitas vezes você nem precisa de uma — o próprio processador já dá conta.",
            "<strong>Armazenamento (SSD ou HD):</strong> é onde os seus arquivos ficam guardados de forma permanente, mesmo com o computador desligado — diferente da memória RAM, que se apaga assim que você desliga o PC. É tipo o armário de arquivos, enquanto a RAM é a mesa de trabalho.",
            "<strong>Fonte de alimentação (às vezes chamada de PSU):</strong> é a peça que pega a energia elétrica da tomada da sua casa e converte na quantidade certa de energia que cada peça do PC precisa pra funcionar.",
            "<strong>Gabinete:</strong> é a 'caixa' de metal e plástico que segura e protege todas as peças por dentro, além de ajudar a circular o ar pra tudo não esquentar demais.",
            "Pronto — com essas sete palavras você já entende a imensa maioria de qualquer conversa sobre montagem de PC. Vamos usar todas elas no resto da trilha, sempre relembrando o que cada uma significa quando precisar.",
        ],
    },
    {
        "slug": "por-onde-comecar",
        "bloco": 2,
        "bloco_nome": "Escolher as Peças",
        "numero": 5,
        "titulo": "Por onde começar a escolha?",
        "resumo": "Definindo o orçamento e o objetivo do PC.",
        "video_url": None,
        "paragrafos": [
            "Antes de olhar qualquer peça específica, responda duas perguntas simples: <strong>quanto eu posso gastar</strong>, e <strong>pra que eu vou usar esse PC</strong>? A resposta dessas duas perguntas praticamente decide todas as escolhas seguintes — é literalmente o que o nosso Montador de PC pergunta pra você antes de sugerir qualquer coisa.",
            "Defina primeiro o valor total que você tem disponível, e já reserve mentalmente uns 10% a 15% desse valor pra imprevistos (frete, um cabo que faltou, uma peça que subiu de preço). É mais fácil planejar de cima pra baixo — 'eu tenho X reais, como divido' — do que ir somando peça por peça sem controle e descobrir no fim que passou do orçamento.",
            "Sobre o objetivo: se é pra <strong>jogos</strong>, o dinheiro deve ir mais pra placa de vídeo e processador. Se é pra <strong>trabalho e edição</strong> (vídeo, design, planilhas pesadas), o foco vai mais pra memória RAM e um processador forte. Se é pra <strong>estudo e uso geral</strong> (aulas online, navegação, textos), dá pra ir bem com uma configuração bem mais simples e barata. Não existe 'o PC perfeito' igual pra todo mundo — existe o PC certo pro que você vai fazer com ele.",
            "Com orçamento e objetivo na cabeça, a ordem lógica de escolher as peças é essa: <strong>1) processador, 2) placa-mãe, 3) memória RAM, 4) placa de vídeo (se precisar), 5) armazenamento, 6) fonte, 7) gabinete.</strong> É exatamente essa ordem que seguimos no resto da trilha, e é a mesma lógica que o Montador de PC usa por trás dos panos.",
        ],
    },
    {
        "slug": "quanto-de-ram",
        "bloco": 2,
        "bloco_nome": "Escolher as Peças",
        "numero": 6,
        "titulo": "Quanto de RAM eu realmente preciso?",
        "resumo": "8GB, 16GB ou 32GB? Saiba o ideal para você.",
        "video_url": None,
        "paragrafos": [
            "<strong>8GB:</strong> hoje já é o mínimo do mínimo, recomendado só pra um uso bem básico — navegar na internet, editar textos, assistir aula online. Se você tentar jogar ou abrir várias coisas ao mesmo tempo, vai sentir o PC travando.",
            "<strong>16GB:</strong> é o valor ideal pra maioria das pessoas hoje em dia. Dá conta bem de jogos atuais, edições mais leves, várias abas do navegador abertas e um pouco de multitarefa no dia a dia sem travar.",
            "<strong>32GB:</strong> vale a pena se você edita vídeo em alta resolução, roda programas de design/engenharia pesados, ou faz transmissão ao vivo (streaming) enquanto joga.",
            "Um detalhe técnico que faz diferença: a quantidade de RAM não é tudo — o número de 'módulos' (também chamados de pentes) também importa. Sempre que der, prefira comprar 2 módulos menores (por exemplo, dois de 8GB) em vez de 1 módulo maior (um de 16GB) pra chegar no mesmo total. Isso ativa um recurso chamado 'dual channel', que deixa o PC mais rápido, principalmente em jogos. Não se preocupe em entender o porquê técnico agora — só lembre da regra: 2 módulos é melhor que 1, pro mesmo total de RAM.",
            "Se você estiver em dúvida entre dois valores, geralmente compensa mais ir pro valor maior. RAM é uma das peças mais fáceis e baratas de trocar depois — mas já começar no nível certo evita dor de cabeça e economiza um upgrade no futuro próximo.",
        ],
    },
    {
        "slug": "cpu-e-placa-mae-compatibilidade",
        "bloco": 2,
        "bloco_nome": "Escolher as Peças",
        "numero": 7,
        "titulo": "Processador e placa-mãe: como garantir que são compatíveis",
        "resumo": "Entenda o que é 'socket' e nunca compre a peça errada.",
        "video_url": None,
        "paragrafos": [
            "Todo processador tem um formato de encaixe chamado <strong>'socket'</strong> — pense nele como o formato de uma tomada elétrica: um plugue de dois pinos não entra numa tomada de três pinos. A placa-mãe também tem um socket, e ele precisa ser exatamente igual ao do processador. Por exemplo, um processador com socket 'LGA1700' só encaixa numa placa-mãe que também seja 'LGA1700'. Não existe adaptador nem jeitinho pra isso — ou é igual, ou não encaixa.",
            "A forma mais simples de nunca errar: escolha primeiro o processador que cabe no seu orçamento e no seu objetivo (lição 5), anote o nome exato do socket dele (está sempre na descrição/ficha técnica da peça, na loja onde você for comprar), e só depois procure uma placa-mãe que tenha esse mesmo socket escrito na descrição dela.",
            "Boa notícia: é exatamente isso que o Montador de PC do KitPC já faz sozinho, de forma automática — quando você escolhe um processador na ferramenta, ela só te mostra placas-mãe com o socket compatível. Assim fica impossível errar essa combinação usando a ferramenta.",
            "Tem uma segunda 'trava' de compatibilidade: o tipo de memória RAM, que pode ser DDR4 ou DDR5. Cada placa-mãe aceita só um desses dois tipos — então confira isso também antes de comprar a memória. De novo, isso também é filtrado automaticamente pelo Montador de PC.",
        ],
    },
    {
        "slug": "ssd-ou-hd",
        "bloco": 2,
        "bloco_nome": "Escolher as Peças",
        "numero": 8,
        "titulo": "SSD ou HD? Quanto de armazenamento escolher",
        "resumo": "A diferença de velocidade é gigante — entenda antes de decidir.",
        "video_url": None,
        "paragrafos": [
            "Um <strong>SSD</strong> (Solid State Drive) não tem peças mecânicas girando por dentro, então ele é muito mais rápido que um HD tradicional: o Windows liga em poucos segundos, em vez de minutos, e os programas abrem quase na hora. Hoje em dia, todo PC novo deveria ter pelo menos um SSD como unidade principal (onde o Windows fica instalado).",
            "Um <strong>HD</strong> (o disco rígido mecânico, mais antigo) ainda faz sentido como armazenamento extra e mais barato, pra guardar arquivos grandes que você não abre toda hora — fotos, vídeos, backups. O preço por cada GB de espaço é bem mais barato que o do SSD.",
            "Sobre quantidade de espaço: <strong>256GB</strong> de SSD é o mínimo aceitável hoje (só o próprio Windows já ocupa uma parte considerável disso). <strong>512GB</strong> é um valor bem confortável pra maioria das pessoas. Se você joga bastante ou trabalha com arquivos grandes (vídeo, design), <strong>1TB (1000GB)</strong> evita que você fique tendo que apagar coisa toda semana pra abrir espaço.",
            "Uma combinação bem comum e inteligente: um SSD menor (256GB ou 512GB) só pra instalar o Windows e os programas, mais um HD grande e barato só pra guardar arquivos. Assim você tem velocidade onde importa (o sistema) e espaço onde é mais barato ter (os arquivos).",
        ],
    },
    {
        "slug": "fonte-de-alimentacao",
        "bloco": 2,
        "bloco_nome": "Escolher as Peças",
        "numero": 9,
        "titulo": "Fonte de alimentação: como calcular a potência certa",
        "resumo": "A peça que ninguém quer comprar, mas que não dá pra economizar.",
        "video_url": None,
        "paragrafos": [
            "A fonte de alimentação é, sem exagero, uma das peças mais subestimadas por quem está começando — e uma das mais importantes de todas. Ela é quem entrega energia pra todas as outras peças do PC. Uma fonte fraca ou de baixa qualidade pode causar desligamentos aleatórios, travamentos, e no pior caso, até danificar outras peças caras.",
            "Pra saber a potência necessária, soma-se o consumo de energia de cada peça (esse consumo é chamado de 'TDP'), principalmente do processador e da placa de vídeo, que são as peças que mais consomem. A regra prática é: pegue esse consumo total estimado e adicione uma folga de 20% a 25% em cima — isso dá espaço pra picos de consumo e faz a fonte trabalhar numa faixa mais eficiente e segura.",
            "Boa notícia de novo: é exatamente esse cálculo que o Montador de PC do KitPC já faz automaticamente pra você. Ele soma o consumo estimado de cada peça que você escolheu e já sugere uma fonte com a potência (e a folga) adequada, sem você precisar calcular nada na mão.",
            "Não economize demais nessa peça específica: uma fonte de marca desconhecida e barata é um dos maiores riscos reais de queimar outras peças caras do seu PC lá na frente. Prefira sempre marcas reconhecidas no mercado, mesmo que isso signifique gastar um pouco mais aqui.",
        ],
    },
    {
        "slug": "ordem-de-montagem",
        "bloco": 3,
        "bloco_nome": "Execução Prática",
        "numero": 10,
        "titulo": "Ordem correta de montagem",
        "resumo": "O que instalar primeiro para não ter que desmontar depois.",
        "video_url": None,
        "paragrafos": [
            "Essa lição é o 'mapa' de toda a montagem física. Seguir essa ordem evita que você tenha que desmontar uma peça no meio do caminho porque outra ficou no caminho dela. Vamos passo a passo, bem devagar.",
            "<strong>Passo 1 — Ainda fora do gabinete, numa mesa:</strong> pegue a placa-mãe e coloque ela em cima da própria caixa de papelão em que ela veio (isso protege ela de riscar a mesa e evita contato direto com superfícies que possam gerar estática). É muito mais fácil encaixar as próximas peças com a placa-mãe deitada numa mesa do que já dentro do gabinete apertado.",
            "<strong>Passo 2 — Processador:</strong> ainda na mesa, abra a trava do soquete (socket) da placa-mãe, encaixe o processador prestando atenção numa setinha ou marcação dourada no canto dele que precisa alinhar com uma marcação igual no soquete, e feche a trava com cuidado. Lembre da regra de ouro: se não entrar fácil, ele está desalinhado — não force, tire e alinhe de novo.",
            "<strong>Passo 3 — Memória RAM:</strong> ainda na mesa, localize os encaixes compridos e estreitos de RAM na placa-mãe. Abra as travinhas nas pontas do encaixe, alinhe o 'chanfro' (um pequeno corte no meio do pente de memória) com o 'ressalto' do encaixe, e empurre os dois lados do pente pra baixo, com firmeza igual dos dois lados, até ouvir um 'clique' e as travinhas fecharem sozinhas.",
            "<strong>Passo 4 — SSD M.2 (se você tiver um):</strong> se sua placa-mãe tem um encaixe SSD M.2 (um slot comprido e fino, geralmente perto do processador), encaixe o SSD nele numa leve diagonal e depois abaixe ele até ficar reto, prendendo com um parafuso pequeno que geralmente já vem preso na própria placa-mãe.",
            "<strong>Passo 5 — Agora sim, dentro do gabinete:</strong> com processador, RAM e SSD já na placa-mãe, coloque a placa-mãe dentro do gabinete, alinhando os furos dela com os pequenos pinos dourados (chamados de 'espaçadores') que já devem estar parafusados dentro do gabinete. Parafuse a placa-mãe nesses pontos, sem apertar demais.",
            "<strong>Passo 6 — Cooler do processador (se for separado):</strong> se o seu cooler não veio já junto com o processador, instale ele agora por cima do processador, seguindo o manual que vem na caixa dele (o método de fixação varia de marca pra marca). Conecte o cabo dele no encaixe da placa-mãe escrito 'CPU_FAN'.",
            "<strong>Passo 7 — Fonte de alimentação:</strong> encaixe a fonte na parte de trás do gabinete (geralmente tem um lugar específico e óbvio pra ela, com um furo quadrado pro ventilador respirar) e parafuse ela no lugar.",
            "<strong>Passo 8 — Placa de vídeo (se você tiver uma):</strong> encaixe ela no slot comprido da placa-mãe chamado 'PCIe' (geralmente o slot mais próximo do processador e mais comprido de todos), empurrando com firmeza até ouvir o clique da travinha, e parafuse ela na parte de trás do gabinete.",
            "<strong>Passo 9 — Todos os cabos por último:</strong> conecte o cabo grande de 24 pinos da fonte na placa-mãe, o cabo menor de 4/8 pinos (energia do processador), os cabos de energia da placa de vídeo (se tiver uma), os cabos do painel frontal (explicamos em detalhe na lição 12) e os cabos de dados/energia de qualquer SSD ou HD extra.",
            "Pronto — essa é a sequência inteira. Parece bastante coisa lida de uma vez, mas fazendo na prática, uma peça de cada vez, sem pressa, cada passo leva só alguns minutos.",
        ],
    },
    {
        "slug": "preparando-ambiente",
        "bloco": 3,
        "bloco_nome": "Execução Prática",
        "numero": 11,
        "titulo": "Preparando o ambiente e evitando estática",
        "resumo": "Cinco minutos de preparo que evitam 90% dos problemas.",
        "video_url": None,
        "paragrafos": [
            "Antes de tocar em qualquer peça, separe 5 minutos pra preparar o ambiente. Isso evita a grande maioria dos problemas que iniciantes têm — e não custa nada.",
            "<strong>Escolha o lugar certo:</strong> uma mesa de madeira firme e livre é ideal. Evite montar em cima da cama, de um tapete ou carpete — esses materiais acumulam eletricidade estática com muita facilidade, e é exatamente essa estática que pode, em teoria, danificar uma peça sensível.",
            "<strong>Descarregue a estática do seu corpo:</strong> antes de tocar em qualquer peça (processador, RAM, placa-mãe), encoste a palma da mão em uma superfície de metal sem pintura — pode ser a própria estrutura interna do gabinete (ainda desligado da tomada) ou a carcaça de um eletrodoméstico ligado na tomada, mas desligado no botão dele. Isso 'zera' a estática acumulada no seu corpo antes que ela chegue na peça.",
            "<strong>Evite tecidos que geram estática:</strong> se puder, evite montar vestindo roupas de lã ou tecido muito sintético, e evite montar em dias muito secos sem repetir o passo anterior mais de uma vez durante a montagem.",
            "<strong>Organize os parafusos:</strong> separe um potinho pequeno ou um pratinho só pra colocar os parafusos conforme for tirando das embalagens. Eles são pequenos e somem fácil numa mesa bagunçada. Guarde as caixas de cada peça até terminar tudo e confirmar que o PC liga normalmente — facilita muito se precisar trocar alguma peça na garantia depois.",
            "Com esses cuidados simples, o risco de estragar alguma peça por estática cai praticamente a zero. Não precisa de nenhum equipamento especial — só atenção nesses detalhes antes de começar a encaixar as peças.",
        ],
    },
    {
        "slug": "cabos-painel-frontal",
        "bloco": 3,
        "bloco_nome": "Execução Prática",
        "numero": 12,
        "titulo": "Conectando os cabos do painel frontal",
        "resumo": "O 'pesadelo' dos iniciantes, explicado com calma.",
        "video_url": None,
        "paragrafos": [
            "Essa é a parte que mais assusta quem está começando — mas só porque ninguém explica com calma. Vamos com tudo bem devagar.",
            "<strong>O que são esses cabos:</strong> são uns fiozinhos bem pequenos e finos que saem de dentro da frente do gabinete. Eles controlam o botão de ligar, o botão de reiniciar (reset), a luz que acende quando o PC está ligado, e a luz que pisca quando o disco está sendo usado. Às vezes também tem cabos de USB e de fone de ouvido da frente do gabinete.",
            "<strong>Onde eles se encaixam:</strong> na placa-mãe, tem uma área pequena, geralmente perto de uma das bordas, com uma fileira de pininhos minúsculos. Ela costuma estar escrita 'F_PANEL', 'Front Panel' ou algo parecido, direto na própria placa-mãe (letrinhas bem pequenas — pode precisar de uma lanterna de celular pra enxergar).",
            "<strong>Onde encontrar o diagrama exato:</strong> toda placa-mãe vem com um manual (impresso na caixa, ou em PDF no site do fabricante — é só pesquisar o nome exato da sua placa-mãe + 'manual pdf'). Esse manual sempre tem um desenho mostrando exatamente qual pininho é qual. Você não precisa decorar nada, só ter esse desenho do lado enquanto conecta.",
            "<strong>Os dois cabos mais fáceis:</strong> o do botão de ligar (POWER SW) e o do botão de reiniciar (RESET SW) não têm um lado certo — funcionam do jeito que você encaixar, não tem como errar esses dois.",
            "<strong>Os dois cabos com lado certo:</strong> a luz de 'ligado' (Power LED) e a luz de atividade do disco (HDD LED) têm um lado positivo e um negativo. Se depois de ligar o PC a luz simplesmente não acender, não é motivo de susto — só desligue o PC, vire esse conector especificamente ao contrário, e ligue de novo. Não tem risco nenhum de dano em fazer isso.",
            "<strong>Dica que evita 90% da frustração:</strong> conecte esses cabos com boa luz (use a lanterna do celular se precisar) e sem pressa nenhuma — como são pinos bem pequenos e próximos uns dos outros, é fácil de errar a posição no escuro ou com pressa. Fazer com calma logo na primeira vez evita ter que desmontar tudo de novo depois pra corrigir.",
        ],
    },
    {
        "slug": "primeira-inicializacao",
        "bloco": 3,
        "bloco_nome": "Execução Prática",
        "numero": 13,
        "titulo": "Primeira inicialização: e se não ligar?",
        "resumo": "Configurando a BIOS e resolvendo os problemas mais comuns.",
        "video_url": None,
        "paragrafos": [
            "Montagem terminada — chegou a hora do primeiro 'vrau'. Antes de ligar, dá uma última olhada rápida: todos os cabos de energia estão bem encaixados? Nenhuma ferramenta ou parafuso solto ficou esquecido dentro do gabinete? Tudo certo, é só ligar o cabo de força na tomada e apertar o botão de ligar do gabinete.",
            "Se deu tudo certo, em poucos segundos deve aparecer uma tela (geralmente com o logo da marca da sua placa-mãe). Aperte a tecla DEL ou F2 repetidamente logo nesse momento pra entrar numa área chamada BIOS (ou UEFI) — é uma espécie de 'painel de controle' básico do computador, que existe antes mesmo do Windows abrir.",
            "Já dentro da BIOS, tem dois ajustes simples que valem a pena fazer: primeiro, procure e ative uma opção chamada <strong>XMP</strong> (em placas de algumas marcas aparece como DOCP ou EXPO) — isso faz sua memória RAM funcionar na velocidade que ela realmente promete, porque sem ativar isso ela roda mais devagar do que deveria por padrão. Segundo, confira se o nome do seu processador aparece corretamente na tela e se a temperatura dele está numa faixa normal, entre 30°C e 50°C, com o PC ligado sem fazer nada de pesado.",
            "<strong>Se o PC simplesmente não ligar</strong> (nenhuma luz, nenhum barulho, tela preta), siga essa ordem pra descobrir o problema, um item de cada vez, sempre desligando da tomada antes de mexer em qualquer cabo: <strong>1)</strong> confira se o cabo de 24 pinos da placa-mãe e o cabo de 4 ou 8 pinos do processador estão bem encaixados até o fim — essa é a causa mais comum de todas. <strong>2)</strong> Tire a memória RAM e encaixe de novo, com força igual nos dois lados até ouvir o clique — às vezes ela simplesmente não entrou até o fim. <strong>3)</strong> Revise os cabos do painel frontal (lição anterior) — às vezes o botão de ligar está no pino errado e por isso parece que 'não liga', quando na real só o botão que não está conectado direito.",
            "Se depois de revisar esses três pontos ainda não funcionar, respire fundo — não é motivo de pânico. A esmagadora maioria dos casos de 'não liga' é cabo mal encaixado ou memória no slot errado, não uma peça quebrada de verdade. Revise com calma, um item de cada vez, sem pressa.",
            "E se ligou e chegou até aqui: parabéns de verdade — você completou a Trilha KitPC do zero ao primeiro boot, e agora tem um PC montado com as próprias mãos. Aproveita o novo PC!",
        ],
    },
]


def get_licao_por_slug(slug):
    """Retorna o dicionário da lição correspondente ao slug, ou None se não existir."""
    return next((licao for licao in LICOES if licao["slug"] == slug), None)