# -*- coding: utf-8 -*-
# Conteúdo da Trilha KitPC: do zero ao primeiro boot.
# Cada lição é um dicionário com: slug (usado na URL), bloco (1, 2 ou 3),
# bloco_nome (título do bloco), numero (ordem de exibição), titulo, resumo
# (aparece na listagem) e paragrafos (corpo da lição, um item por parágrafo).

LICOES = [
    {
        "slug": "pc-arriscado",
        "bloco": 1,
        "bloco_nome": "Começar do Zero (Perder o Medo)",
        "numero": 1,
        "titulo": "Montar um PC é arriscado?",
        "resumo": "Quebrando o medo de perder dinheiro e queimar peças.",
        "paragrafos": [
            "A primeira pergunta que quase todo iniciante faz é: 'e se eu quebrar alguma coisa?'. A boa notícia é que montar um PC é muito mais seguro do que parece. As peças modernas são projetadas com encaixes que só entram de um jeito — se algo não está entrando fácil, é sinal de que está na posição errada, não de que você precisa forçar.",
            "O maior risco real não é quebrar uma peça por engano de montagem, e sim a eletricidade estática do seu próprio corpo. Por isso vamos falar de descarga estática mais pra frente na trilha (lição 11) — é simples de evitar e resolve 90% do medo de 'queimar' algo.",
            "Regra de ouro que vale pra trilha inteira: se você precisa fazer força pra encaixar uma peça, pare e confira se está no lugar certo. Encaixe correto entra com pouca pressão. Isso vale pro processador, pra memória RAM, pros cabos — tudo.",
            "Com calma, seguindo a ordem certa (que a gente também vai te mostrar), o risco de dano é muito baixo. Milhares de pessoas sem experiência nenhuma montam seus primeiros PCs todo santo dia — você vai conseguir também.",
        ],
    },
    {
        "slug": "pronto-ou-montar",
        "bloco": 1,
        "bloco_nome": "Começar do Zero (Perder o Medo)",
        "numero": 2,
        "titulo": "PC pronto ou montar peça por peça?",
        "resumo": "Vantagens, desvantagens e custo-benefício.",
        "paragrafos": [
            "Um PC pronto (vendido já montado por uma loja ou fabricante) tem a vantagem óbvia da praticidade: chega em casa, liga e usa. Em compensação, você paga por esse serviço, e muitas vezes as peças usadas são versões mais baratas do que pareceria pelo preço final.",
            "Montar peça por peça exige mais estudo (é pra isso que essa trilha existe) e um pouco mais de tempo, mas o ganho em custo-benefício costuma ser real: você escolhe exatamente onde investir mais (por exemplo, numa placa de vídeo melhor) e onde economizar (num gabinete mais simples).",
            "Tem também o fator aprendizado: quem monta o próprio PC entende melhor como resolver problemas depois — trocar uma peça, fazer upgrade, diagnosticar um defeito. Isso tem valor a longo prazo, mesmo que o primeiro PC não seja perfeito.",
            "Não existe resposta certa universal. Se seu objetivo é só ter um computador funcionando o quanto antes e orçamento não é o maior problema, PC pronto resolve. Se você quer aprender, tem tempo disponível e quer aproveitar melhor cada real investido, montar você mesmo vale a pena — e é pra isso que o Montador do KitPC e essa trilha existem.",
        ],
    },
    {
        "slug": "ferramentas-necessarias",
        "bloco": 1,
        "bloco_nome": "Começar do Zero (Perder o Medo)",
        "numero": 3,
        "titulo": "Ferramentas que você realmente precisa",
        "resumo": "O que separar antes de começar (e o que você não precisa comprar).",
        "paragrafos": [
            "A boa notícia: montar um PC não exige uma caixa de ferramentas cheia. Na prática, 90% da montagem se resolve com uma única chave Phillips (aquela de ponta em cruz) de tamanho médio, tipo #2.",
            "Itens que ajudam bastante e são baratos: uma superfície de trabalho firme (mesa, não a cama ou o carpete), boa iluminação, e um recipiente pequeno pra não perder os parafusos que sobram.",
            "Sobre pulseira antiestática: ela é recomendada, mas não é obrigatória se você tomar um cuidado simples — antes de tocar nas peças, encoste com a mão em alguma parte metálica não pintada do gabinete ou de um eletrodoméstico aterrado. Isso descarrega a estática do seu corpo.",
            "O que você NÃO precisa comprar: kits de chaves de precisão para eletrônica, pasta térmica extra (a maioria dos coolers já vem com uma camada aplicada de fábrica), ou ferramentas especializadas de informática. Se sobrar dinheiro, prefira investir numa peça melhor do que em ferramentas que você vai usar uma vez.",
        ],
    },
    {
        "slug": "glossario-basico",
        "bloco": 1,
        "bloco_nome": "Começar do Zero (Perder o Medo)",
        "numero": 4,
        "titulo": "Glossário rápido: os termos que todo iniciante ouve",
        "resumo": "CPU, GPU, RAM, SSD, fonte, placa-mãe — o que cada peça faz, em português simples.",
        "paragrafos": [
            "<strong>Processador (CPU):</strong> é o 'cérebro' do computador. Ele executa os cálculos e comandos que fazem tudo funcionar — de abrir um programa a rodar um jogo.",
            "<strong>Placa-mãe:</strong> é a base onde todas as outras peças se encaixam. Ela decide quais processadores e memórias são compatíveis com o seu PC (por isso a lição 7 é tão importante).",
            "<strong>Memória RAM:</strong> é a 'mesa de trabalho' do computador — onde ficam os dados dos programas abertos no momento. Mais RAM significa mais coisas rodando ao mesmo tempo sem travar.",
            "<strong>Placa de vídeo (GPU):</strong> processa imagens e gráficos. Essencial pra jogos e edição de vídeo/imagem; dispensável pra uso básico de escritório e estudos.",
            "<strong>Armazenamento (SSD/HD):</strong> é onde os arquivos ficam guardados permanentemente, mesmo com o PC desligado. É diferente da RAM, que se apaga quando você desliga.",
            "<strong>Fonte de alimentação (PSU):</strong> converte a energia da tomada em energia que as peças conseguem usar, na quantidade certa pra cada uma.",
            "<strong>Gabinete:</strong> a 'caixa' que abriga e protege todas as peças, além de ajudar na ventilação.",
            "Com esses sete termos você já entende a imensa maioria das conversas sobre montagem de PC. Vamos usar todos eles no resto da trilha.",
        ],
    },
    {
        "slug": "por-onde-comecar",
        "bloco": 2,
        "bloco_nome": "Escolher as Peças",
        "numero": 5,
        "titulo": "Por onde começar a escolha?",
        "resumo": "Definindo o orçamento e o objetivo do PC.",
        "paragrafos": [
            "Antes de olhar qualquer peça específica, responda duas perguntas: quanto eu posso gastar, e pra que eu vou usar esse PC? Essas duas respostas guiam literalmente todas as escolhas seguintes — é exatamente o que o nosso Montador de PC pergunta antes de sugerir qualquer coisa.",
            "Defina o orçamento total primeiro, e reserve mentalmente uma pequena margem (10-15%) pra imprevistos ou upgrades de última hora. É mais fácil planejar de cima pra baixo (tenho X reais, como distribuo) do que ir somando peça por peça e descobrir no final que estourou o teto.",
            "Sobre o objetivo: 'jogos' pede mais investimento em placa de vídeo e processador; 'trabalho e edição' pede mais RAM e um processador forte; 'estudos e uso geral' pode ir bem com uma configuração bem mais simples e barata. Não existe 'PC perfeito universal' — existe o PC certo pro que você vai fazer com ele.",
            "Com orçamento e objetivo definidos, a ordem lógica de escolha das peças costuma ser: processador → placa-mãe → memória RAM → placa de vídeo (se precisar) → armazenamento → fonte → gabinete. É a ordem que seguimos no resto dessa trilha.",
        ],
    },
    {
        "slug": "quanto-de-ram",
        "bloco": 2,
        "bloco_nome": "Escolher as Peças",
        "numero": 6,
        "titulo": "Quanto de RAM eu realmente preciso?",
        "resumo": "8GB, 16GB ou 32GB? Saiba o ideal para você.",
        "paragrafos": [
            "<strong>8GB:</strong> hoje já é o mínimo recomendável, ideal só pra uso bem básico — navegação, documentos, videoaulas. Jogos e multitarefa pesada vão sentir o aperto.",
            "<strong>16GB:</strong> é o ponto ideal pra maioria das pessoas em 2026. Dá conta bem de jogos atuais, edição leve, várias abas abertas e multitarefa no dia a dia sem travar.",
            "<strong>32GB:</strong> vale a pena pra quem edita vídeo em resolução alta, roda máquinas virtuais, trabalha com programas pesados de design/engenharia, ou faz streaming enquanto joga.",
            "Um detalhe técnico importante: a quantidade de RAM é só metade da história — a velocidade e o número de módulos (pentes) também importam. Sempre que possível, prefira 2 pentes (por exemplo, 2x8GB em vez de 1x16GB) — isso ativa o modo 'dual channel', que aumenta bastante a performance em jogos.",
            "Se está em dúvida entre dois valores, geralmente vale mais a pena ir pro valor maior do que economizar aqui — RAM é uma das peças mais fáceis (e baratas) de fazer upgrade depois, mas já começar no nível certo evita dor de cabeça.",
        ],
    },
    {
        "slug": "cpu-e-placa-mae-compatibilidade",
        "bloco": 2,
        "bloco_nome": "Escolher as Peças",
        "numero": 7,
        "titulo": "Processador e placa-mãe: como garantir que são compatíveis",
        "resumo": "Entenda o que é 'socket' e nunca compre a peça errada.",
        "paragrafos": [
            "Todo processador tem um tipo de encaixe físico chamado 'socket'. A placa-mãe também tem um socket, e eles precisam ser exatamente iguais — um processador Intel com socket LGA1700, por exemplo, só encaixa numa placa-mãe que também seja LGA1700. Não existe adaptador ou 'jeitinho' aqui.",
            "A forma mais simples de não errar: escolha primeiro o processador que cabe no seu orçamento e objetivo, anote o nome exato do socket dele (está sempre na ficha técnica), e depois procure placas-mãe compatíveis com esse mesmo socket.",
            "Isso é exatamente o que o Montador de PC do KitPC já faz automaticamente por você: ao escolher um processador, ele só sugere placas-mãe com o socket compatível — assim é impossível errar essa combinação usando a ferramenta.",
            "Uma segunda camada de compatibilidade: o tipo de memória RAM (DDR4 ou DDR5) também depende da placa-mãe. Cada placa aceita só um dos dois tipos, então confira isso antes de comprar a memória — de novo, o Montador já filtra isso automaticamente.",
        ],
    },
    {
        "slug": "ssd-ou-hd",
        "bloco": 2,
        "bloco_nome": "Escolher as Peças",
        "numero": 8,
        "titulo": "SSD ou HD? Quanto de armazenamento escolher",
        "resumo": "A diferença de velocidade é gigante — entenda antes de decidir.",
        "paragrafos": [
            "Um SSD (Solid State Drive) não tem partes móveis, então é muito mais rápido que um HD tradicional — o Windows liga em segundos em vez de minutos, e os programas abrem quase instantaneamente. Hoje em dia, praticamente todo PC novo deveria ter pelo menos um SSD como unidade principal.",
            "HD (disco rígido mecânico) ainda faz sentido como armazenamento secundário e barato, pra guardar arquivos grandes que você não abre toda hora — fotos, vídeos, backups. O custo por GB é bem menor que o do SSD.",
            "Sobre quantidade: 256GB de SSD é o mínimo aceitável hoje (só o Windows já ocupa uma boa parte). 512GB é um valor confortável pra maioria das pessoas. Se você joga bastante ou trabalha com arquivos grandes, 1TB evita que você fique apagando coisa toda hora pra abrir espaço.",
            "Uma combinação comum e inteligente: um SSD menor (256GB-512GB) só pra Windows e programas, mais um HD grande e barato pra arquivos. Isso dá velocidade onde importa e espaço onde é barato.",
        ],
    },
    {
        "slug": "fonte-de-alimentacao",
        "bloco": 2,
        "bloco_nome": "Escolher as Peças",
        "numero": 9,
        "titulo": "Fonte de alimentação: como calcular a potência certa",
        "resumo": "A peça que ninguém quer comprar, mas que não dá pra economizar.",
        "paragrafos": [
            "A fonte de alimentação é, sem exagero, uma das peças mais subestimadas por iniciantes — e uma das mais importantes. Ela entrega energia pra todas as outras peças, e uma fonte fraca ou de má qualidade pode causar desligamentos aleatórios, instabilidade, ou até danificar componentes.",
            "Pra calcular a potência necessária, soma-se o consumo (TDP) de cada peça, principalmente processador e placa de vídeo, que são as que mais consomem. Regra prática: pegue o consumo total estimado e adicione uma margem de 20-25% de folga — isso dá espaço pra picos de consumo e pra a fonte trabalhar numa faixa de eficiência melhor.",
            "É exatamente esse cálculo que o Montador do KitPC faz automaticamente ao montar sua configuração — ele soma o TDP estimado de cada peça escolhida e já sugere uma fonte com potência (e folga) adequada.",
            "Não economize demais aqui: uma fonte de marca desconhecida e baixa qualidade é um dos maiores riscos reais de queimar outras peças caras do seu PC. Prefira marcas reconhecidas, mesmo que isso signifique gastar um pouco mais nessa peça específica.",
        ],
    },
    {
        "slug": "ordem-de-montagem",
        "bloco": 3,
        "bloco_nome": "Execução Prática",
        "numero": 10,
        "titulo": "Ordem correta de montagem",
        "resumo": "O que instalar primeiro para não ter que desmontar depois.",
        "paragrafos": [
            "Seguir a ordem certa evita ter que desmontar peças no meio do caminho porque alguma coisa ficou no caminho de outra. A sequência mais tranquila pra quem está começando é: 1) processador na placa-mãe, 2) memória RAM na placa-mãe, 3) SSD M.2 na placa-mãe (se tiver), tudo isso ainda fora do gabinete.",
            "Depois disso, instala-se a placa-mãe (já com essas três peças) dentro do gabinete, seguida do cooler (se for separado do processador) e da fonte de alimentação.",
            "Por último entram a placa de vídeo (no slot PCIe da placa-mãe) e todos os cabos: energia da placa-mãe, energia do processador, cabos do painel frontal, e cabos de dados/energia de SSDs e HDs adicionais.",
            "Montar a placa-mãe com processador, RAM e SSD fora do gabinete primeiro (numa mesa, sobre a própria caixa da placa-mãe) é mais fácil e mais seguro do que tentar encaixar essas peças já dentro do gabinete apertado — guarde essa dica, ela poupa muita frustração.",
        ],
    },
    {
        "slug": "preparando-ambiente",
        "bloco": 3,
        "bloco_nome": "Execução Prática",
        "numero": 11,
        "titulo": "Preparando o ambiente e evitando estática",
        "resumo": "Cinco minutos de preparo que evitam 90% dos problemas.",
        "paragrafos": [
            "Escolha uma superfície firme, plana e não condutiva — uma mesa de madeira funciona bem. Evite montar em cima de carpete, tapete ou tecido, que acumulam eletricidade estática facilmente.",
            "Antes de tocar em qualquer peça, encoste com a mão em uma superfície metálica aterrada — a carcaça de um eletrodoméstico ligado na tomada (mas desligado no botão), por exemplo, ou o próprio gabinete metálico já conectado à fonte (sem ligar na tomada ainda). Isso descarrega a estática do seu corpo.",
            "Evite usar roupas de lã ou tecidos muito sintéticos enquanto monta, e se possível, evite montar em dias muito secos sem tomar esse cuidado extra com a descarga estática.",
            "Mantenha os parafusos organizados (um potinho ou a própria embalagem de cada peça ajuda) e guarde as caixas das peças até terminar a montagem e confirmar que tudo funciona — facilita eventuais trocas em garantia.",
            "Com esses cuidados simples, o risco de dano por estática cai praticamente a zero. Não precisa de equipamento especial, só atenção nesses detalhes antes de começar.",
        ],
    },
    {
        "slug": "cabos-painel-frontal",
        "bloco": 3,
        "bloco_nome": "Execução Prática",
        "numero": 12,
        "titulo": "Conectando os cabos do painel frontal",
        "resumo": "O 'pesadelo' dos iniciantes, explicado com calma.",
        "paragrafos": [
            "Os cabos do painel frontal são aqueles fiozinhos pequenos que saem da frente do gabinete (botão liga/desliga, botão reset, LED de energia, LED de atividade do disco, e às vezes USB/áudio frontal). Eles costumam vir em conectores minúsculos e mal identificados — daí a fama de pesadelo.",
            "A boa notícia: o manual da sua placa-mãe (físico ou em PDF no site do fabricante) sempre tem um diagrama exato mostrando onde cada pino vai, na região chamada 'Front Panel' ou 'F_PANEL'. Vale a pena consultar em vez de tentar adivinhar.",
            "Os conectores de POWER SW e RESET SW não têm polaridade — funcionam em qualquer posição. Já os LEDs (Power LED e HDD LED) têm lado positivo e negativo; se o LED não acender, geralmente basta inverter o conector, sem risco de dano.",
            "Dica prática: monte os cabos do painel frontal com a placa-mãe ainda fora do gabinete ou com boa iluminação e sem pressa — são pinos pequenos e é fácil errar de posição no escuro ou com pressa. Fazer isso com calma logo de início evita ter que desmontar depois.",
        ],
    },
    {
        "slug": "primeira-inicializacao",
        "bloco": 3,
        "bloco_nome": "Execução Prática",
        "numero": 13,
        "titulo": "Primeira inicialização: e se não ligar?",
        "resumo": "Configurando a BIOS e resolvendo os problemas mais comuns.",
        "paragrafos": [
            "Montagem terminada, é hora do primeiro 'vrau'. Ligue na tomada, aperte o botão de força e, se tudo deu certo, você deve ver a tela da BIOS/UEFI logo nos primeiros segundos (aperte DEL ou F2 repetidamente ao ligar pra entrar nela).",
            "Já dentro da BIOS, dois ajustes importantes: ative o perfil XMP (ou DOCP/EXPO, dependendo da marca) pra sua memória RAM funcionar na velocidade anunciada — sem isso ela roda mais devagar do que deveria. E confira se o processador está sendo reconhecido corretamente e as temperaturas estão numa faixa normal (30°C-50°C em repouso).",
            "Se não ligar de jeito nenhum: primeiro confira os cabos de energia (24 pinos da placa-mãe e 4/8 pinos do processador) — é a causa mais comum. Depois, tente reencaixar a memória RAM em outro slot, um pente de cada vez. Por último, revise os cabos do painel frontal (lição anterior) — o botão de power pode estar no pino errado.",
            "Se mesmo assim não funcionar, não é motivo de pânico: a esmagadora maioria dos casos de 'não liga' é cabo mal encaixado ou memória RAM no slot errado, não peça danificada. Revise com calma, um item de cada vez.",
            "Chegando até aqui, parabéns — você completou a Trilha KitPC do zero ao primeiro boot! Agora é hora de aproveitar seu novo PC.",
        ],
    },
]


def get_licao_por_slug(slug):
    """Retorna o dicionário da lição correspondente ao slug, ou None se não existir."""
    return next((licao for licao in LICOES if licao["slug"] == slug), None)